from typing import Any, Optional

def patch_all(double_patch: bool = ...) -> None: ...
def patch(modules_to_patch: Any, raise_errors: bool = ..., ignore_module_patterns: Optional[Any] = ...) -> None: ...
