from typing import Any, Optional
from aws_xray_sdk.core.models.subsegment import Subsegment

class AWSXRayRecorder:
    def __init__(self) -> None: ...
    def begin_subsegment(self, name: Any, namespace: str = ...) -> Subsegment: ...
    def current_subsegment(self) -> Subsegment: ...
    def end_subsegment(self, end_time: Optional[Any] = ...) -> None: ...
    def begin_segment(self, name: Any, namespace: str = ...) -> Subsegment: ...
    def end_segment(self, end_time: Optional[Any] = ...) -> None: ...
    @property
    def context(self) -> Any: ...
    @property
    def max_trace_back(self) -> int: ...
