from typing import Any, Dict

def construct_xray_header(headers: Dict[str, str]) -> Any: ...
def calculate_segment_name(host_name: str, recorder: Any) -> str: ...
def prepare_response_header(origin_header: Any, segment: Any) -> str: ...
