from typing import Dict, Set, Iterable

class TopologicalSorter:
    def __init__(self, graph: Dict[str, Set[str]]): ...
    def prepare(self) -> None: ...
    def static_order(self) -> Iterable[str]: ...

class CycleError(Exception): ...
