from typing import ContextManager

def mock_apigateway() -> ContextManager[None]: ...
def mock_athena() -> ContextManager[None]: ...
def mock_cloudformation() -> ContextManager[None]: ...
def mock_cloudwatch() -> ContextManager[None]: ...
def mock_cognitoidp() -> ContextManager[None]: ...
def mock_dynamodb() -> ContextManager[None]: ...
def mock_events() -> ContextManager[None]: ...
def mock_glue() -> ContextManager[None]: ...
def mock_iam() -> ContextManager[None]: ...
def mock_kms() -> ContextManager[None]: ...
def mock_lambda() -> ContextManager[None]: ...
def mock_logs() -> ContextManager[None]: ...
def mock_ram() -> ContextManager[None]: ...
def mock_s3() -> ContextManager[None]: ...
def mock_secretsmanager() -> ContextManager[None]: ...
def mock_ses() -> ContextManager[None]: ...
def mock_sns() -> ContextManager[None]: ...
def mock_sqs() -> ContextManager[None]: ...
def mock_stepfunctions() -> ContextManager[None]: ...
def mock_sts() -> ContextManager[None]: ...
def mock_xray() -> ContextManager[None]: ...
